# Generated by Django 5.2.4 on 2025-07-30 10:16

import myapp.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='name',
            field=models.CharField(max_length=100, validators=[myapp.validator.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='crop',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[myapp.validator.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='crop',
            name='variety',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[myapp.validator.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='reason',
            field=models.CharField(max_length=255, validators=[myapp.validator.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='buyer',
            field=models.CharField(max_length=100, validators=[myapp.validator.validate_only_letters]),
        ),
    ]
